### PR TITLE
Implemented unset_header

### PR DESCRIPTION
**Pull request by kmesserig**
To do several tests in a row with existing and missing headers like  authorization, unset_header will remove a list of existing headers.

### CODE REVIEW

**Comment by asyrjasalo** [comment]
I think this PR has potential to shake my "25 keywords at maximum in a library" opinion...

Add some well placed atests and the keyword documentation - particular if there are differences to using `Set Headers` - and then let's get 1.0.2 out.

**Comment by kmesserig** [comment]
Sure good point with the 25 keywords. Maybe it would make more sense to support this feature in the Set Headers keyword it self. Because as of now there was no way to remove the headers from the requests.

**Comment by asyrjasalo** [comment]
Yes, that's why I think `Unset Headers` would be much useful addition too.

I don't think having 25 keywords as a hard limit makes sense if we can have useful keywords for real life use cases. More like, I rather would not start including a separate keyword for each custom HTTP API authentication though, if we can find a generic way to tackle that with a single keyword instead.

I think the original reasoning was to not bloat the library keyword documentation too much to find the correct keyword as fast as possible. But this will get much easier in any case when editors/IDEs will get better support via https://microsoft.github.io/language-server-protocol/ for Robot Framework.

Having some documentation and tests is better than no documentation and tests. Otherwise this looks good.

**Comment by kmesserig** [comment]
Closing this pull request due to some library blow up issues as discussed.

**Comment by asyrjasalo** [comment]
Pardon, I did not get. What you mean by blow up issues?

**Comment by Tset-Noitamotua** [comment]
I guess Anssi did not meant that this one should be closed, did you? @anssi

What about a clear option that would default to false so that when u want
unset headers u do:

`Set Headers    clear=True`

?

Anssi Syrjäsalo <notifications@github.com> schrieb am Fr., 23. Aug. 2019,
19:15:

**Comment by asyrjasalo** [comment]
Closing this pull request due to lack of tests and documentation.

**Pull request closed without merging**
