### PR TITLE
Add OpenApi v3 validator

### PR DESCRIPTION
**Pull request by Kimamisa**

### CODE REVIEW

**Comment by asimell** [comment]
Hi @Kimamisa.

Can you also open the same PR to https://github.com/eficode/RESTinstance? While we're waiting for repository ownership transfer (ping @asyrjasalo ) we're handling PRs but first merging them to the Eficode fork, then creating a release PR to this repo, which is then released.

**Comment by Kimamisa** [comment]
Sure ! 
Here it is: https://github.com/eficode/RESTinstance/pull/10

**Comment by asyrjasalo** [comment]
This does not work anymore with openapi-core 0.19.2. Maybe the library API has changed?

Merging this requires tests to pass.

**Comment by asyrjasalo** [comment]
Closing as inactive. Please reopen pull request if you are willing to work on this.

**Pull request closed without merging**
